# 1. The Deployment defines your application pods
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      containers:
      - name: web
        image: gcr.io/google-samples/hello-app:1.0
        ports:
        - containerPort: 8080

---
# 2. The Service triggers the AWS Load Balancer creation
apiVersion: v1
kind: Service
metadata:
  name: sample-service
  annotations:
    # Specifies that AWS should provision an NLB (Network Load Balancer)
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    # Set to "internal" if you don't want it public
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
spec:
  type: LoadBalancer
  selector:
    app: sample-app
  ports:
    - protocol: TCP
      port: 80        # The port the Load Balancer listens on
      targetPort: 8080 # The port the app container listens on
